#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use Data::Dumper;
use CHI;

my $cache = CHI->new(
  driver => 'Memcached',
  servers => [ 'localhost:11211' ],
);

my $mp = $cache->get("M:Mid+Bedfordshire");

say Dumper $mp;
